#!/usr/bin/env python3
"""
Interactive topic curation tool for podcast graphs.

Reads the auto-generated topics.json produced by generate_entity_graphs.py,
presents each topic for human review, and saves curated labels to
topic_labels.json. The main pipeline and frontend will prefer curated
labels when available.

Usage:
    uv run scripts/curate_topics.py                          # default: graphs/topics.json
    uv run scripts/curate_topics.py --topics-file path/to/topics.json
    uv run scripts/curate_topics.py --labels-file path/to/topic_labels.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

script_dir = Path(__file__).resolve().parent
if str(script_dir) not in sys.path:
    sys.path.insert(0, str(script_dir))

import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Prompt, Confirm

console = Console()


def _display_topic(topic: dict, index: int, total: int) -> None:
    """Display a single topic for review."""
    topic_id = topic["topic_id"]
    words = topic.get("topic_words", [])
    episodes = topic.get("episodes", [])
    label = topic.get("topic_label", f"Topic {topic_id}")
    rep_docs = topic.get("representative_docs", [])

    # header
    console.print(f"\n[bold cyan]━━━ Topic {index + 1}/{total} (id={topic_id}) ━━━[/bold cyan]")
    console.print(f"[bold]Auto-label:[/bold] {label}")
    console.print(f"[bold]Episodes:[/bold]  {len(episodes)}")

    # keywords table
    if words:
        console.print(f"\n[bold]Top words:[/bold] {', '.join(words[:10])}")

    # episode list
    if episodes:
        console.print(f"\n[bold]Episodes in this topic:[/bold]")
        for ep in episodes[:8]:
            title = ep.replace("_", " ").title()
            console.print(f"  • {title}")
        if len(episodes) > 8:
            console.print(f"  [dim]...and {len(episodes) - 8} more[/dim]")

    # representative excerpts
    if rep_docs:
        console.print(f"\n[bold]Sample excerpts:[/bold]")
        for doc in rep_docs[:2]:
            ep_title = doc["episode"].replace("_", " ").title()
            excerpt = doc["excerpt"][:200]
            console.print(Panel(
                f"[dim]{ep_title}[/dim]\n{excerpt}",
                width=min(console.width, 90),
                padding=(0, 1),
            ))


def _prompt_label(topic: dict, existing_label: str | None) -> str | None:
    """Prompt user for a curated label. Returns label, 'discard', or None to keep auto."""
    if existing_label:
        console.print(f"\n[yellow]Current curated label:[/yellow] {existing_label}")

    console.print(
        "\n[bold]Actions:[/bold] "
        "[green]Enter a label[/green] | "
        "[dim]press Enter to keep auto-label[/dim] | "
        "[red]'d' to discard[/red] | "
        "[yellow]'m<id>' to merge into topic <id>[/yellow]"
    )
    response = Prompt.ask("Label", default="").strip()

    if not response:
        return None  # keep auto
    if response.lower() == "d":
        return "__discard__"
    if response.lower().startswith("m") and response[1:].strip().isdigit():
        return f"__merge__{response[1:].strip()}"
    return response


def _display_summary(labels: dict, discarded: list, merged: dict) -> None:
    """Display summary of all curations."""
    console.print("\n[bold cyan]━━━ Curation Summary ━━━[/bold cyan]")

    table = Table()
    table.add_column("Topic ID", style="cyan", justify="right")
    table.add_column("Curated Label", style="green")
    table.add_column("Status", style="yellow")

    for tid, label in sorted(labels.items(), key=lambda x: int(x[0])):
        table.add_row(tid, label, "✓ labeled")

    for tid in sorted(discarded, key=int):
        table.add_row(str(tid), "—", "✗ discarded")

    for src, dst in sorted(merged.items(), key=lambda x: int(x[0])):
        table.add_row(src, f"→ Topic {dst}", "↗ merged")

    console.print(table)


@click.command()
@click.option(
    "--topics-file",
    type=click.Path(path_type=Path),
    default=Path("graphs/topics.json"),
    help="Path to topics.json generated by the pipeline.",
)
@click.option(
    "--labels-file",
    type=click.Path(path_type=Path),
    default=None,
    help="Path to save/load topic_labels.json (default: same directory as topics-file).",
)
def curate_topics(topics_file: Path, labels_file: Path | None) -> None:
    """Interactively review and label auto-generated topics."""

    if not topics_file.exists():
        console.print(f"[bold red]Error: {topics_file} not found.[/bold red]")
        console.print("Run the pipeline first: uv run scripts/generate_entity_graphs.py --visualize")
        sys.exit(1)

    with topics_file.open() as f:
        topics_data = json.load(f)

    topics = topics_data.get("topics", [])
    metrics = topics_data.get("metrics", {})

    if not topics:
        console.print("[bold yellow]No topics found in topics.json.[/bold yellow]")
        sys.exit(0)

    # resolve labels file path
    if labels_file is None:
        labels_file = topics_file.parent / "topic_labels.json"

    # load existing curations if present
    existing_labels: dict[str, str] = {}
    existing_discarded: list[str] = []
    existing_merged: dict[str, str] = {}

    if labels_file.exists():
        with labels_file.open() as f:
            existing = json.load(f)
            existing_labels = existing.get("labels", {})
            existing_discarded = [str(x) for x in existing.get("discarded", [])]
            existing_merged = {str(k): str(v) for k, v in existing.get("merged", {}).items()}
        console.print(f"[dim]Loaded existing curations from {labels_file}[/dim]")

    # display overview
    console.print(Panel(
        f"[bold]Topics:[/bold] {len(topics)}  "
        f"[bold]Episodes:[/bold] {metrics.get('total_episodes', '?')}  "
        f"[bold]Diversity:[/bold] {metrics.get('topic_diversity', '?')}  "
        f"[bold]Outliers:[/bold] {metrics.get('num_outlier_episodes', '?')}\n\n"
        f"For each topic, you can assign a human-readable label,\n"
        f"discard it (hide from frontend), or merge it into another topic.",
        title="Topic Curation",
        width=min(console.width, 90),
    ))

    # curate each topic
    labels = dict(existing_labels)
    discarded = list(existing_discarded)
    merged = dict(existing_merged)

    for i, topic in enumerate(topics):
        tid = str(topic["topic_id"])

        _display_topic(topic, i, len(topics))

        existing_label = labels.get(tid)
        result = _prompt_label(topic, existing_label)

        if result is None:
            # keep existing or auto
            if tid not in labels:
                console.print("[dim]  → keeping auto-label[/dim]")
        elif result == "__discard__":
            if tid in labels:
                del labels[tid]
            if tid not in discarded:
                discarded.append(tid)
            if tid in merged:
                del merged[tid]
            console.print("[red]  → discarded[/red]")
        elif result.startswith("__merge__"):
            target = result.replace("__merge__", "")
            if tid in labels:
                del labels[tid]
            if tid in discarded:
                discarded.remove(tid)
            merged[tid] = target
            console.print(f"[yellow]  → merged into topic {target}[/yellow]")
        else:
            labels[tid] = result
            if tid in discarded:
                discarded.remove(tid)
            if tid in merged:
                del merged[tid]
            console.print(f"[green]  → labeled: {result}[/green]")

    # display summary
    _display_summary(labels, discarded, merged)

    # save
    if Confirm.ask("\nSave curations?", default=True):
        output = {
            "labels": labels,
            "discarded": [int(x) for x in discarded],
            "merged": {int(k): int(v) for k, v in merged.items()},
        }
        with labels_file.open("w") as f:
            json.dump(output, f, indent=2)
        console.print(f"[bold green]✓[/bold green] Saved to {labels_file}")
    else:
        console.print("[dim]Curations not saved.[/dim]")


if __name__ == "__main__":
    curate_topics()
